project:
  type: website

website:
  title: "Projeto SpectraPop"
  favicon: images/favicon.ico

  navbar:
    left:
      - text: "Início"
        href: index.qmd
        
      - text: "Cursos"
        menu:
          - text: "1º Curso (2025)"
            href: cursos/cursomicronir1.qmd
          - text: "2º Curso (2025)"
            href: cursos/cursomicronir2.qmd
          - text: "3º Curso (2026)"
            href: cursos/cursomicronir3.qmd
          - text: "4º Curso (2026)"
            href: cursos/cursoauxiliardecampo.qmd
          - text: "Galeria de Fotos"
            href: cursos/galeria.qmd

      - text: "Produção Intelectual"
        href: producaointelectual.qmd
      
      - text: "Biblioteca Espectral"
        href: bibliotecaespectral.qmd
      
      - text: "Herbário INPA"
        href: herbarioinpa.qmd
        
      - text: "Blog"
        menu:
          - text: "SpectraPop em um esforço global de digitalização espectral"
            href: posts/spectrapop-em-um-esforco-global-de-digitalizacao-espectral.qmd
            
          - text: "Nasce o projeto HerbSpectra-Amazônia"
            href: posts/nasce-o-projeto-herbspectra-amazonia.qmd
            
          - text: "Conheça nossos alunos de Iniciação Científica (PIBIC/INPA 2025–2026)"
            href: posts/conheca-nossos-pibics-2025.qmd
            
          - text: "Novo artigo confirma o potencial da espectroscopia na Amazônia"
            href: posts/novo-artigo-confirma-o-potencial-da-espectroscopia-na-amazonia.qmd
     
      - text: "Galeria de Fotos"
        href: galeria.qmd         
     
      - text: "Contato"
        href: contato.qmd
    
  page-footer:
    center: "Todos os direitos reservados © 2026. Projeto SpectraPop - Grupo de Estudos Espectrais e Ecofisiológicos da Biodiversidade (BiodivSpEc)."

format:
  html:
    lightbox: true
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "Nesta página"
